### ISSUE TITLE
Add a general setup context which is only ran once

### ISSUE THREAD

**Issue by CPerezz** [markhildreth/test-context#12]
It would be nice to have some sort of setup that gets just run once at the beggining of the execution (kinda off like a lazy_static) but that has all of the great properties that the `async_traits` provide with the `&mut ctx`.

This would really help when the setups for testing become too heavy to be executed one time before each test execution.

What do you think? Would it make sense? Has it been explored before?

**Comment by markhildreth** [comment]
@CPerezz To answer your question, I have not explored this idea too much. My hope is that if someone had this need they would be able to implement it by using those types of tools directly (e.g., `Once` or a library like `async_once`) inside of their context's `setup` method. This keeps this library simple (which is good for me since I don't really have that much time to spend on it).
